import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { IChildProcessExecutor } from './executor.js';

export class Packager {
  constructor(private readonly executor: IChildProcessExecutor) {}

  generateReadme(area: string, sources: string[], attribution: string): string {
    return `# ${area} 3D City Model Pack

## Overview

This package contains 3D city model assets derived from PLATEAU open data for the ${area} area.
The assets are provided in FBX, glTF, and USD formats with multiple LOD levels.

## Contents

- \`fbx/\` — FBX format assets (Unity, Unreal Engine compatible)
- \`gltf/\` — glTF format assets (Web/Three.js compatible)
- \`usd/\` — USD format assets (Apple ARKit, Pixar compatible)

## License

This package uses data from the following sources:

${attribution}

Please refer to LICENSE.md for full license terms.

## Usage

- Unity: Import FBX files directly into your project
- Unreal Engine: Use the FBX importer
- Blender: Import glTF or FBX files

## Data Sources

${sources.map((s) => `- ${s}`).join('\n')}

Generated by GeoAutonome Pipeline
`;
  }

  generateLicenseMd(attribution: string): string {
    return `# License

${attribution}

## Disclaimer

This package is provided "as is" without warranty of any kind.
The 3D models are derived from PLATEAU open data and may not perfectly represent current conditions.

Please refer to the original data sources for full license terms.
`;
  }

  async pack(
    assets: string[],
    outputZip: string,
    readme: string,
    licenseMd: string,
  ): Promise<string> {
    const tempDir = path.join(path.dirname(outputZip), '_pack_temp');
    await mkdir(tempDir, { recursive: true });

    await writeFile(path.join(tempDir, 'README.md'), readme, 'utf8');
    await writeFile(path.join(tempDir, 'LICENSE.md'), licenseMd, 'utf8');

    const zipName = path.basename(outputZip);
    const zipDir = path.dirname(outputZip);

    const result = await this.executor.exec('zip', [
      '-r',
      zipName,
      path.relative(zipDir, tempDir),
      ...assets.map((a) => path.relative(zipDir, a)).filter((a) => a.length > 0),
    ], zipDir);

    if (result.exitCode !== 0) {
      throw new Error(`zip command failed: ${result.stderr}`);
    }

    return outputZip;
  }
}
