import path from 'node:path';
import type { IChildProcessExecutor } from '../pipeline/executor.js';
import type { OsakaArea, OsakaMegaPack } from './area-config.js';

export class BundleCreator {
  constructor(private readonly executor: IChildProcessExecutor) {}

  generateMegaPackReadme(areas: OsakaArea[], pack: OsakaMegaPack, attribution: string): string {
    const areaList = areas
      .sort((a, b) => a.priorityOrder - b.priorityOrder)
      .map((a) => `- **${a.displayName}** ($${a.priceUsd}) — \`${a.productName}.zip\``)
      .join('\n');

    const perAreaPrice = areas[0]?.priceUsd ?? 0;
    const totalIndividual = perAreaPrice * areas.length;

    return `# ${pack.displayName}

**Bundle Price**: $${pack.priceUsd} (Individual packs: $${perAreaPrice} each × ${areas.length} = $${totalIndividual})

## Included Areas

${areaList}

## Overview

This bundle contains 3D city model assets for ${areas.length} Osaka areas derived from PLATEAU open data.
All assets are provided in FBX, glTF, and USD formats with multiple LOD levels.

## Contents

Each area pack includes:
- \`fbx/\` — FBX format assets (Unity, Unreal Engine compatible)
- \`gltf/\` — glTF format assets (Web/Three.js compatible)
- \`usd/\` — USD format assets (Apple ARKit, Pixar compatible)

## License

${attribution}

## Usage

1. Extract the area pack(s) you need
2. Import FBX files into Unity or Unreal Engine
3. Or use glTF files for web/Three.js projects

Generated by GeoAutonome Pipeline
`;
  }

  async createBundle(zipPaths: string[], outputZip: string): Promise<string> {
    const zipName = path.basename(outputZip);
    const zipDir = path.dirname(outputZip);

    const relPaths = zipPaths.map((p) => path.relative(zipDir, p));

    const result = await this.executor.exec('zip', ['-r', zipName, ...relPaths], zipDir);

    if (result.exitCode !== 0) {
      throw new Error(`Bundle creation failed: ${result.stderr}`);
    }

    return outputZip;
  }
}
